### ISSUE TITLE
Sentry Request Limits

### ISSUE THREAD

**Issue by heimweh** [jianyuan/terraform-provider-sentry#148]
Hi! Loving the provider so far :raised_hands: 

I encountered an issue yesterday when trying to manage a large group of services inside one stack:

> Error: sentry: You are attempting to use this endpoint too frequently. Limit is 40 requests in 1 seconds

I'm using the project and team resources and this seems to be happening inside Read functions, which causes the plan to eventually fail. Would it make sense to add some retry handling inside the Read functions? :pray: 

Happy to contribute any fixes if needed :slightly_smiling_face:

**Comment by Dyhr** [comment]
I'm also having this issue. The plan fails randomly, so it feels like the provider trying to send up to 40 requests per second, but if the connection is even a little unreliable then sometimes more than 40 arrive within a second. Just a hypothesis though.

I assume it's a timing issue since there is a rate limiter in the config, so maybe a quick solution is if we can adjust the rate limit ourselves to something slightly lower?

**Comment by gberenice** [comment]
We're facing the issue as well. 
@Dyhr thanks for the proposal 👍

**Comment by jianyuan** [comment]
Fixed in https://github.com/jianyuan/terraform-provider-sentry/pull/168!

**Comment by olhabilan** [comment]
Hi!

we're still experiencing the issue related to rate limits
```
429 API rate limit of 40 and concurrent limit of 25 still exceeded until 2022-07-04 12:57:55 +0000 UTC, not making remote request.
```
@jianyuan could you please take a look?

**Comment by dwilliams782** [comment]
Can confirm we see the above too, getting around it with `-parallelism=1`

**Comment by jianyuan** [comment]
@olhabilan @dwilliams782 Can you confirm the version of the provider that you are using?

**Comment by dwilliams782** [comment]
I was seeing that on the latest, 0.9.0. We've since reverted to 0.6.0 (long story, not because of an issue with the provider)

**Comment by olhabilan** [comment]
We are using 0.9.2 version

**Comment by olhabilan** [comment]
@jianyuan have you had a chance to take a look at this issue?

**Comment by jianyuan** [comment]
This is fixed in v0.9.3 🎉
